In [12]:
import numpy as np;

A=np.array([[1,2],[3,4]])
B=np.array([[4,6],[7,8]])

print("Matrix operation")
print(f"matrix A:\n{A}")
print(f"matrix B:\n{B}")
print(f"matrix addintion:\n{A+B}")
print(f"matrix substration:\n{A-B}")
print(f"matrix dot product:\n{A*B}")
print(f"matrix transpose:\n{A.T}")

Matrix operation
matrix A:
[[1 2]
 [3 4]]
matrix B:
[[4 6]
 [7 8]]
matrix addintion:
[[ 5  8]
 [10 12]]
matrix substration:
[[-3 -4]
 [-4 -4]]
matrix dot product:
[[ 4 12]
 [21 32]]
matrix transpose:
[[1 3]
 [2 4]]
